openapi: 3.0.0
info:
  description: This API provides health checks
  version: "1.0.0"
  title: Valorant Efficiency Health Check API
  contact:
    email: justin.taan@gmail.com
paths:
  /health:
    get:
      tags:
        - health check
      summary: reports health check
      description: Returns 200 response code if the app is running
      operationId: app.health_check
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/health_check'
  
components:
  schemas:
    health_check:
      type: object
      required:
        - receiver
        - storage
        - audit
        - processing
        - last_updated
      properties:
        receiver:
          type: string
          example: running
        storage:
          type: string
          example: running
        audit:
          type: string
          example: running
        processing:
          type: string
          example: running
        last_updated:
            type: string
            format: date-time
            example: '2016-08-29T09:12:33.001Z'