openapi: 3.0.0
info:
  description: This API provides health checks
  title: Valorant Efficiency Health Check API
  contact:
    email: justin.taan@gmail.com
paths:
  /health:
    get:
      summary: reports health check
      description: Returns 200 response code if the app is running
      operationId: app.health_check
      response:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "App is running smoothly"
